### ISSUE TITLE
Programmierung bei Programmänderung

### ISSUE THREAD

**Issue by hurzl** [hampelratte/lazybones#10]
Jetzt sind die Tagesthemen 1/4 h später als im tvbrowser angegeben. Wenn ich die programmieren will, bekomme ich die Auswahl und wähle Tagesthemen. Trotzdem nimmt er den vorangehenden Film auf. 
(Version 1.3.4)

**Comment by hampelratte** [comment]
Kann ich mit einem manipulierten EPG nachvollziehen. Ich habe einfach einen Brennpunkt wie gestern eingeschoben. Wenn man nicht die Timeroptions beim Anlegen eines Timers anzeigen lässt, ergibt sich genau das Verhalten. Ich schaue mir das mal an.

**Comment by hampelratte** [comment]
Ist in Version 1.4 gefixt.

**Comment by hurzl** [comment]
saaagenhaft :)

**Comment by hurzl** [comment]
Was ist jetzt los, Sendungen von gestern hat er nicht aufgenommen, dafür sind sie heute noch im Timer?

**Comment by hampelratte** [comment]
Schau mal, ob der Timer für Februar gesetzt wurde. Das Problem hatte ich gestern. Ist ein Problem mit den Datums-APIs. TV-Browser zählt Monate von 1-12, Java von 0-11.

**Comment by hurzl** [comment]
ja, ich habs gesehen, der letzte commit ist aber leider nicht im paket dabei

**Comment by hurzl** [comment]
danke!
