### ISSUE TITLE
Falsche recording number

### ISSUE THREAD

**Issue by MehrCurry** [hampelratte/lazybones#13]
Hallo,

ich versuche gerade mir die Aufnahmen mit VLC anzusehen. Dabei musste ich feststellen, dass VLC mit einer falschen recording number gestartet wird. Die Nummer ist ein eine Stelle zu kurz. Wenn ich die URLs überprüfe, stelle ich fest, dass die letzte Stelle nicht an VLC übergeben wird.

Aus 113 wird 11, aus 95 wird 9, u.s.w.

KODI/VDR: Openelec 6.0.3
TV-Browser: 3.4.3
Lazybones: 1.5.1.0

URL für den VLC Aufruf: `http://openelec:3000/2049:<recording_number>.rec`

**Comment by hampelratte** [comment]
Wenn Du versuchst eine Aufnahme abzuspielen und danach mal in den Einstellungen für Lazy Bones unter Allgemein das Log öffnest, taucht dort auch die falsche Nummer auf?

Falls ja, könntest Du mir dann die Ausgabe folgendes Befehls schicken?
 ```bash
telnet openelec 6419
lstr
quit
```

**Comment by MehrCurry** [comment]
Danke, deine Tipps haben mich in die richtige Richtung geführt.

Der Fehler saß mal wieder vor dem Bildschirm. Ich hatte das Pattern für das Abspielen der Aufnahmen aus dem RSS Feed `http://openelec:3000/recordings.rss` abgeschrieben:

```
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
	<channel>
		<title>VDR</title>
		<link>http://openelec:3000/recordings.html</link>
		<description>VDR channel list</description>

		<item>
			<title>1 31.01.16 15:30  Stubbe - Von Fall zu Fall</title>
			<link>http://openelec:3000/2049:14.rec</link>
			<enclosure url="http://openelec:3000/2049:14.rec" type="video/mpeg" />
		</item>

		<item>
			<title>2 04.02.16 20:15  Mythbusters - Die Wissensjäger</title>
			<link>http://openelec:3000/2049:33.rec</link>
			<enclosure url="http://openelec:3000/2049:33.rec" type="video/mpeg" />
		</item>
...
	</channel>
</rss>
```
Also `http://openelec:3000/2049:<recording_number>.rec` Bei dieser URL hängt aber hinter der recoding_number noch eine weitere Ziffer, deren Herkunft mir nicht klar ist.

Ich habe die URL jetzt ganz simpel geändert auf `http://openelec:3000/<recording_number>.rec`. Und nun gehts.

Du kannst den Punkt gerne schließen. Danke.
