### ISSUE TITLE
NPE unter Linux

### ISSUE THREAD

**Issue by MehrCurry** [hampelratte/lazybones#14]
Hallo,

ich betreibe TV-Browser + Lazybones auf einem Raspberry PI 3 unter raspian.

Funktioniert fast perfekt, nur bei der Anzeige der Timer gibt es ein Problem. Im HTML Pane steht "can't load template for details"

Per Remote-Debug habe ich die schuldige Zeile gefunden:

`AbstractDetailsPanel.java`
```
private String replaceColors(String template) {
        template = template.replaceAll("\\{backgroundColor\\}", toHexString(UIManager.getColor("TextArea.background")));
        template = template.replaceAll("\\{textColor\\}", toHexString(UIManager.getColor("TextArea.foreground")));
        template = template.replaceAll("\\{textInactiveColor\\}", toHexString(UIManager.getColor("TextArea.inactiveForeground")));
        return template;
    }
```

Der letzte Aufruf zur Bestimmung der "inactiveForeground" Color liefert bei mit `null`.

Kann ich irgendwas tun (linux.properties) oder ist das ein Bug?

**Comment by hampelratte** [comment]
Es könnte sein, dass das Look and Feel, das Du nutzt, diese Farbe nicht gesetzt hat. Versuch mal in den TV-Browser-Einstellungen unter Grafische Einstellungen ein anderes Thema. Ich selbst benutze Plastic XP mit Sky Blue Farbschema.

Welches verwendest Du?

Das ist ganz klar ein Bug. Das muss ich abfangen.

**Comment by MehrCurry** [comment]
Ich habe jetzt tatsächlich in der linux.properties das `Plastic3DLookAndFeel` aktiviert und nun gibt es keine Exception mehr. Ist aber nur ein Workaround.

Ich habe mich selber mal mit dem JGoodies Zeug beschäftigt, ist aber ewig her. Das Default L&F unter Linux scheint die entsprechende Farbe nicht zu definieren.

**Comment by hampelratte** [comment]
Genau wie ich gedacht habe. Beim Nimbus LaF tritt der Fehler bei mir auch auf.

**Comment by MehrCurry** [comment]
Im TV Browser sind noch die Defaults eingetragen: Plastic 3D und Sky Blue.

Seltsamerweise habe ich in der linux.properties auch Plastic 3D eingetragen ... löst aber das Problem.
