### ISSUE TITLE
Monat wird beim Anlegen eines Timers nicht berücksichtigt

### ISSUE THREAD

**Issue by zimuland** [hampelratte/lazybones#17]
Wahrscheinlich nur ein Problem im Februar, in den anderen Monaten reichen die EPG-Daten im TV-Browser wahrscheinlich nicht weit genug in die Zukunft.
Am 04.02. habe ich versucht, einen Timer für eine Sendung am 04.03. zu programmieren. Dabei wurde der Timer für den 04.02. angelegt.

**Comment by hampelratte** [comment]
Das ist eine Limitation, die es in alten VDR-Versionen gab. Dort konnte / musste der Tag einzeln angegeben werden. Also z.B. nicht 2022-02-25, sondern nur 25. Ab einer bestimmten Version (, die ich noch nicht herausgesucht habe) kann man dann das vollständige Datum benutzen. LazyBones weiß allerdings schon mit welcher VDR-Version es spricht. Ich könnte also eine Unterscheidung je nach Version einbauen. Ich schaue mir das mal an.

**Comment by hampelratte** [comment]
Tatsächlich war das Feature seit 2011 in der svdrp4j Bibliothek implementiert. Allerdings war ich da nicht weitsichtig genug, so dass das neue Format nur für VDR-Versionen zwischen 1.3.23 und 2.0.0 benutzt wurde.

Zusätzlich gab es auch noch einen Bug in Lazy Bones selbst. Version 1.7.2 habe ich eben hochgeladen. Damit sollte es jetzt funktionieren.
