### ISSUE TITLE
Don't close player after TV-Browser is closed

### ISSUE THREAD

**Issue by troych** [hampelratte/lazybones#5]
Would it be possible to leave the desired media player open when it's still playing LiveTV even if you close TV-Browser?

I don't know if thats a limitation or by design, I keep forgetting that my player will close when I still like to watch TV but don't need the TV-Browser any more.

Greetings from Switzerland

**Comment by hampelratte** [comment]
I have been mistaken on the behaviour. In the next version there will be a toggle in the settings to keep the player open, when TV-Browser is closed.
